inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

# Rails用に最適化
Rails:
  Enabled: true

#rubocopで検証したくないフォルダを指定
AllCops:
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "config/environments/*"
    - "config/application.rb"
    - "config/initializers/*"
    - "config/spring.rb"
    - "lib/tasks/*"
    - "vendor/**/*"
    - "path/ruby"
    - "node_modules/node-sass/src/libsass/contrib/libsass.spec"

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# クラスのコメント必須を無視
Style/ClassAndModuleChildren:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 文字数の上限を８０文字から変更
Metrics/LineLength:
  Max: 130

# 複数行での「lambda」で「->」による省略記法を許可
Style/Lambda:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視
Style/FrozenStringLiteralComment:
  Enabled: false
