version: "3"
services:
  db:
    image: postgres:12.4-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo

  web:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/gunpla-type
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      RAILS_SYSTEM_TESTING_SCREENSHOT: inline
    stdin_open: true
    tty: true
    depends_on:
      - db

  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   links:
  #     - web
  #   restart: always
  #   environment:
  #     DOMAINS: "web.local -> http://web:3000"
  #     STAGE: local
  #   depends_on:
  #     - web
