version: "3"
services:
  db:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo

  web:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/gunpla-type
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_SYSTEM_TESTING_SCREENSHOT=inline
    stdin_open: true
    tty: true
