version: 2.1
jobs:
  rubocop:
    working_directory: ~/gunpla-type
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - save_cache:
          paths:
            - ./vendor/bundle
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
  rspec:
    working_directory: ~/gunpla-type
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose stop
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up -d
      - run:
          name: Run Rspec
          command: docker-compose exec web rspec
      - run:
          name: docker-compose down
          command: docker-compose down

  heroku_deploy:
    working_directory: ~/gunpla-type
    docker:
      - image: circleci/ruby:2.7.1-node
    steps:
      - checkout
      - run:
          name: Install Heroku CLI
          command: |
            if [[ $(dommand -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: heroku maintenance on
          command: heroku maintenance:on --app ${HEROKU_APP_NAME}
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: heroku maintenance off
          command: heroku maintenance:off --app ${HEROKU_APP_NAME}
      # - run:
      #     name: Run post-deploy tasks
      #     command: |
      #       heroku run bin/rails db:migrate
      #       heroku run bin/rails runner db/seeds

# workflows:
#   version: 2.1
#   rubocop_rspec:
#     jobs:
#       - rubocop
#       - rspec:
#           requires:
#             - rubocop
workflows:
  version: 2.1
  deploy:
    jobs:
      - heroku_deploy:
        filters:
          branches:
            only:
              - circleci-project-setup
