defaults: &defaults
  working_directory: ~/gunpla-type
  docker:
    - image: circleci/ruby:2.7.1-buster-node-browsers
      environment:
        BUNDLE_PATH: vendor/bundle
        TZ: "/usr/share/zoneinfo/Asia/Tokyo"

version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
            - v1-bundle-
      - run:
          name: bundle and yarn install
          command: |
            gem install bundler
            bundle check || bundle install --clean --jobs=4 --retry=3
            yarn install
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - vendor/bundle
            - node_modules
      - persist_to_workspace:
          root: ~/gunpla-type
          paths:
            - ./*

  code_analyze:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/gunpla-type
      - run:
          name: Run rubocop
          command: bundle exec rubocop --require rubocop-airbnb --parallel
      - run:
          name: Run rails_best_practices
          command: bundle exec rails_best_practices
      - run:
          name: Run brakeman
          command: bundle exec brakeman

  rspec:
    working_directory: ~/gunpla-type
    docker:
      - image: circleci/ruby:2.7.1-buster-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      - image: circleci/postgres:11.7
        environment:
          POSTGRES_PASSWORD: password
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
    parallelism: 2
    steps:
      - attach_workspace:
          at: ~/gunpla-type
      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libappindicator1 fonts-liberation
            export CHROME_BIN=/usr/bin/google-chrome
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome*.deb
      - run:
          name: Create db
          command: bundle exec rake db:create db:schema:load --trace
          environment:
            RAILS_ENV: test
      - run:
          name: Run Rspec
          command: |
            bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
          environment:
            RAILS_ENV: test

  heroku_deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/gunpla-type
      - run:
          name: Install Heroku CLI
          command: |
            if [[ $(dommand -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: heroku maintenance on
          command: heroku maintenance:on --app ${HEROKU_APP_NAME}
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: Set RAILS_MASTER_KEY
          command: heroku config:set RAILS_MASTER_KEY=$RAILS_MASTER_KEY --app ${HEROKU_APP_NAME}
      - run:
          name: heroku db migrate
          command: heroku run rails db:migrate:reset --app ${HEROKU_APP_NAME}
      - run:
          name: heroku maintenance off
          command: heroku maintenance:off --app ${HEROKU_APP_NAME}

workflows:
  version: 2.1
  workflows:
    jobs:
      - build
      - code_analyze:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
      - rspec:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
      - heroku_deploy:
          requires:
            - code_analyze
            - rspec
          filters:
            branches:
              ignore:
                - master
